name: Save Product Details to File

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering from the Actions tab

jobs:
  save-to-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python (for file manipulation, or you can use another language)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies (if needed)
      # If you're using any libraries to handle the data, install them here
      # - run: pip install <your dependencies>

      # Step 4: Update the text file with your data
      - name: Update Text File
        run: |
          echo "Adding new product details..." >> products.txt
          echo "Name: New Product, Price: $10.00, Stock: 100" >> products.txt

      # Step 5: Commit and push changes back to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add products.txt
          git commit -m "Updated products.txt with new product details"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
